//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class reversiEntities : DbContext
    {
        public reversiEntities()
            : base("name=reversiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kupci> kupci { get; set; }
        public virtual DbSet<roba> roba { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<racuni> racuni { get; set; }
        public virtual DbSet<revroba> revroba { get; set; }
    
        public virtual ObjectResult<p_get_stock_level_Result> p_get_stock_level()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_get_stock_level_Result>("p_get_stock_level");
        }
    
        public virtual ObjectResult<p_get_stock_level2_Result> p_get_stock_level2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_get_stock_level2_Result>("p_get_stock_level2");
        }
    }
}
