//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class racuni
    {
        public string brev { get; set; }
        public System.DateTime datum { get; set; }
        public string idbrojk { get; set; }
        public string idbrojr { get; set; }
        public decimal kolu { get; set; }
        public decimal kolv { get; set; }
        public decimal cena { get; set; }
        public decimal utro { get; set; }
    
        public virtual kupci kupci { get; set; }
        public virtual roba roba { get; set; }
    }
}
