//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class RevRoba
    {
        public int RevRobaID { get; set; }
        public int RacuniID { get; set; }
        public System.DateTime Datum { get; set; }
        public int RobaID { get; set; }
        public Nullable<decimal> Kolic { get; set; }
        public Nullable<int> Utro { get; set; }
        public decimal Cena { get; set; }
    
        public virtual Racuni racuni { get; set; }
        public virtual Roba roba { get; set; }
    }
}
