//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class revroba
    {
        public int pk { get; set; }
        public int brev { get; set; }
        public System.DateTime datum { get; set; }
        public int idbrojr { get; set; }
        public Nullable<decimal> kolu { get; set; }
        public Nullable<decimal> kolv { get; set; }
        public Nullable<decimal> utro { get; set; }
        public decimal cena { get; set; }
    
        public virtual racuni racuni { get; set; }
        public virtual roba roba { get; set; }
    }
}
