//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class viewracuni
    {
        public string brev { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string ime { get; set; }
        public string naziv { get; set; }
        public Nullable<decimal> kolu { get; set; }
        public Nullable<decimal> kolv { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<decimal> cena { get; set; }
        public Nullable<decimal> utro { get; set; }
    }
}
